### ISSUE TITLE
Cannot build app with this SDK without data@scheme attribute in AndroidManifest

### ISSUE THREAD

**Issue by pkrawczykObj** [okta/okta-devices-kotlin#43]
### Describe the bug?

Cannot build a project after adding implementation("com.okta.devices:devices-push:0.0.2") dependency to the project, with following error:

`Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <webAuthenticationRedirectScheme> is provided.`

Thanks to the sample app I found out that it can be fixed by adding to app's build.gradle:
`manifestPlaceholders["webAuthenticationRedirectScheme"] = "XXX"`

But I don't understand why it is needed and there is nothing about it in the integration guide here:
https://developer.okta.com/docs/guides/authenticators-custom-authenticator/android/main/#install-and-configure-the-okta-devices-sdk

In my use case I just want to use the PUSH Notifications as a second factor of auth and I already have OKTA integrated with this library https://github.com/openid/AppAuth-Android for authorisation.

### What is expected to happen?

Project builds after adding this library with no extra dependencies.

### What is the actual behavior?

Project cannot be built.

### Reproduction Steps?

Add `implementation("com.okta.devices:devices-push:0.0.2") `dependency to the project

### SDK Version and Artifact(s) used.

0.0.2

### Build Information

gradle:7.2.0

**Comment by FeiChen-okta** [comment]
@pkrawczykObj The oidc sdk is a required dependency for the sample app. It is used to get an access token to enroll push. 
The user has to login first to be able to enroll in push.
See the integration guide https://developer.okta.com/docs/guides/authenticators-custom-authenticator/android/main/#create-an-oidc-web-authentication-client

**Comment by pkrawczykObj** [comment]
@FeiChen-okta  Thank you for the response. 

I'm using OKTA in my app and I just want to add Push Notifications as a second factor of authentication, so I have the valid `accessToken` stored in my app and I don't need to add another OIDC Client like in the sample app.

When I am trying to enroll to the pushes I firstly log in with the email as a second factor and I am retrieving the newest `accessToken`. Then I try to use it to enroll for the PUSHes and with:

1. build.gradle value:
`manifestPlaceholders["webAuthenticationRedirectScheme"] = "x-as24-pkce://callback/success"`

When I call `com.okta.devices.push.api.PushAuthenticator.enroll(AuthToken.Bearer(accessToken), config, params)` I get following error:
`Failure(com.okta.devices.api.errors.DeviceAuthenticatorError$InternalDeviceError:;error code: CL000000; summary:; cause: java.io.IOException: Invalid HTTP statusCode 401 )`

2. build.gradle value:
`manifestPlaceholders["webAuthenticationRedirectScheme"] = "x-as24-pkce"`

I got the same error and in addition I got two prompts from Android system to choose the app to handle the redirect intent, both showing my app, which is not good.

**Comment by FeiChen-okta** [comment]
Hi @pkrawczykObj Which authorization server are you using?
[custom authorization](https://developer.okta.com/docs/concepts/auth-servers/#default-custom-authorization-server) servers are not yet supported.

Can you also list the scopes for the access token?

It looks like you are mixing the AppAuth and the Okta oidc SDK. It is registering two activity to handle the redirect. The SampleApp uses the okta sdk to get a access token. Since your application is using AppAuth, you don't need to add the okta sdk, remove the following from your gradle file:
```
    implementation(platform("com.okta.kotlin:bom:1.0.0"))
    implementation("com.okta.kotlin:auth-foundation")
    implementation("com.okta.kotlin:oauth2")
    implementation("com.okta.kotlin:web-authentication-ui")
```
You also don't need:
```
manifestPlaceholders["webAuthenticationRedirectScheme"] = "x-XXX-pkce://callback/success"
```

**Comment by pkrawczykObj** [comment]
Hi @FeiChen-okta, I was trying to use `https://auth-XXX.OUR_ORG.com/oauth2/default/v1/authorize`, but then I found out that the `default` is also custom authorization server so I change to  `https://auth-XXX.OUR_ORG.com/oauth2/v1/authorize` with following scopes:
`            "openid",
            "profile",
            "email",
            "offline_access",
            "okta.authenticators.manage.self",
            "okta.authenticators.read",
            "okta.users.read.self"`
            
With this config I am receiving the following error:
`The grant was issued for another authorization server.
    AuthorizationException: {"type":2,"code":2000,"error":"invalid_request","errorDescription":"The grant was issued for another authorization server.","errorUri":""}`         
    
Because in the AuthorizationService Configuration I still had:  `https://MY_ORG.okta.com/oauth2/default`, so I removed the `default`, but then I received following error:
```
Network error when retrieving discovery document
    java.io.FileNotFoundException: https://MY_ORG.okta.com/oauth2/.well-known/openid-configuration
```
My OKTA Admin says, that he cannot add the configuraton file to the URL above, since it is OKTA Server.
How we can proceed?

Thank you for the answer about mixing the AppAuth and the Okta oidc SDK. The double intent issues is now gone, but I am still struggling to finish enrollment.

**Comment by FeiChen-okta** [comment]
Hi @pkrawczykObj Unfortunately this is a known limitation of the beta release.
https://developer.okta.com/docs/guides/authenticators-custom-authenticator/android/main/#grant-the-required-scopes

The backend does not yet allow custom authorization integration, this will be added when we finish beta. Currently you can integrate with the org auth server for initial integration with the SDK, once custom authorization servers is supported the switch should be a simple config change to point to your auth server. Please reach out to your customer support rep for more information on release dates, etc.

**Comment by pkrawczykObj** [comment]
This issue can be closd, now it is working
